<?php
$title = $this->translate('Login');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('loginname'));
echo $this->formRow($form->get('loginpassword'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>